Repository apple/swift-cluster-membership, pull requests merged in 2025-05, with the labels that each got.

#117 Drop Swift 5.9
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
  Package.swift
  Samples/Package.swift
Labels: 🆕 semver/minor

#120 Add support for Musl static Linux SDK
  Sources/SWIM/SWIMInstance.swift
  Sources/SWIM/SWIMProtocol.swift
  Sources/SWIM/Settings.swift
  Sources/SWIM/Utils/Heap.swift
Labels: 🔨 semver/patch

#112 Add static SDK CI workflow
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: semver/none
